NUMPY

class name of numpy is ndarray

Numpy is a Python library used for working with arrays

In Python we have liste that serves the purpose of arrays, but they are

slow to procese.

Numpy aims to provide an array object that is up to 50° faster than

traditional Python lists.

The array object in Numpy is called ndarray, it provides a lot of

supporting functions that make working with ndarray very easy

Arrays are very frequently used in data science, where speed and

resources are very important

Collection of homogenous data

It does not support heterogenous data

In [1]:
import numpy as np

x = np.ndarray([1, 2, 3, 5,6])

print(x)



[[[[[6.53776234e-310 6.53776234e-310 4.98000163e-310 4.98000163e-310
     6.53776203e-310 6.53776206e-310]
    [6.53776203e-310 6.53774094e-310 6.53774094e-310 6.53776206e-310
     6.53776199e-310 6.53776206e-310]
    [6.53776203e-310 6.53776203e-310 6.53774094e-310 6.53774094e-310
     6.53776192e-310 6.53776203e-310]
    [6.53776192e-310 6.53774094e-310 6.53776206e-310 6.53776199e-310
     6.53776206e-310 6.53776206e-310]
    [6.53774094e-310 6.53776192e-310 6.53776190e-310 6.53774094e-310
     6.53776166e-310 9.53546696e-322]]

   [[6.53776234e-310 6.53776234e-310 6.53776198e-310 6.53776206e-310
     6.53776206e-310 6.53776206e-310]
    [6.53774094e-310 6.53776203e-310 6.53776199e-310 6.53776203e-310
     6.53776203e-310 6.53776203e-310]
    [6.53776192e-310 6.53776192e-310 6.53776192e-310 6.53776166e-310
     6.53776206e-310 6.53776192e-310]
    [6.53776203e-310 6.53776203e-310 6.53776203e-310 6.53776190e-310
     2.13436359e-321 5.13828272e-321]
    [6.53774146e-310 6.53774146e-31

In [2]:
import numpy as np

x = np.array([1, 2, 5,6])

print(x)


[1 2 5 6]


In [3]:
print(type(x))

<class 'numpy.ndarray'>


In [4]:
print(x.ndim)

1


In [5]:
print(x.shape)

(4,)


2-Dimension array

In [6]:
import numpy as np

x = np.array([[1, 2, 5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 5 6]]
(1, 4)
2


In [7]:
import numpy as np

x = np.array([[1,2,5,6],[1,2,5,6]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 5 6]
 [1 2 5 6]]
(2, 4)
2


In [8]:
import numpy as np

x = np.array([[1,2,3,8,10],[1,2,3,8,10],[1,2,3,8,10],[1,2,3,8,10]])

print(x)
print(x.shape)
print(x.ndim)

[[ 1  2  3  8 10]
 [ 1  2  3  8 10]
 [ 1  2  3  8 10]
 [ 1  2  3  8 10]]
(4, 5)
2


In [9]:
import numpy as np

x = np.array([[1,2,5,6,5,3],[1,2,5,6,5,3]])

print(x)
print(x.shape)
print(x.ndim)

[[1 2 5 6 5 3]
 [1 2 5 6 5 3]]
(2, 6)
2


#group of 2D forms 3D

In [10]:
x = np.array([[[2,4,5],[7,17,20]],[[2,4,5],[7,17,20]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  4  5]
  [ 7 17 20]]

 [[ 2  4  5]
  [ 7 17 20]]]
<class 'numpy.ndarray'>
3
(2, 2, 3)


In [11]:
x = np.array([[[2,4],[7,17],[5,6],[7,6]],[[2,4],[7,17],[5,6],[7,6]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  4]
  [ 7 17]
  [ 5  6]
  [ 7  6]]

 [[ 2  4]
  [ 7 17]
  [ 5  6]
  [ 7  6]]]
<class 'numpy.ndarray'>
3
(2, 4, 2)


In [12]:
x = np.array([[[2,4,7],[7,17,8]],[[2,4,7],[7,17,8]],[[2,4,7],[7,17,8]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  4  7]
  [ 7 17  8]]

 [[ 2  4  7]
  [ 7 17  8]]

 [[ 2  4  7]
  [ 7 17  8]]]
<class 'numpy.ndarray'>
3
(3, 2, 3)


In [13]:
x = np.array([[[2,4],[7,17]],[[2,4],[7,17]],[[2,4],[7,17]],[[2,4],[7,17]]])

print(x)
print(type(x))
print(x.ndim)
print(x.shape)

[[[ 2  4]
  [ 7 17]]

 [[ 2  4]
  [ 7 17]]

 [[ 2  4]
  [ 7 17]]

 [[ 2  4]
  [ 7 17]]]
<class 'numpy.ndarray'>
3
(4, 2, 2)


In [14]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.zeros((2,3,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [16]:
np.zeros((2,3,4),dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [17]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [19]:
np.ones((2,3,4),dtype=int)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

In [20]:
np.arange(20,80,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75])

In [21]:
np.linspace(20,80,8)

array([20.        , 28.57142857, 37.14285714, 45.71428571, 54.28571429,
       62.85714286, 71.42857143, 80.        ])

In [22]:
np.linspace(20,80)

array([20.        , 21.2244898 , 22.44897959, 23.67346939, 24.89795918,
       26.12244898, 27.34693878, 28.57142857, 29.79591837, 31.02040816,
       32.24489796, 33.46938776, 34.69387755, 35.91836735, 37.14285714,
       38.36734694, 39.59183673, 40.81632653, 42.04081633, 43.26530612,
       44.48979592, 45.71428571, 46.93877551, 48.16326531, 49.3877551 ,
       50.6122449 , 51.83673469, 53.06122449, 54.28571429, 55.51020408,
       56.73469388, 57.95918367, 59.18367347, 60.40816327, 61.63265306,
       62.85714286, 64.08163265, 65.30612245, 66.53061224, 67.75510204,
       68.97959184, 70.20408163, 71.42857143, 72.65306122, 73.87755102,
       75.10204082, 76.32653061, 77.55102041, 78.7755102 , 80.        ])

In [23]:
np.full((3,4),70,dtype=float)

array([[70., 70., 70., 70.],
       [70., 70., 70., 70.],
       [70., 70., 70., 70.]])

In [24]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
np.random.random((3,2,2))

array([[[0.80685517, 0.3178923 ],
        [0.06798373, 0.32537517]],

       [[0.988114  , 0.53328636],
        [0.3131398 , 0.7186158 ]],

       [[0.95770326, 0.78361965],
        [0.78575637, 0.24264217]]])

In [26]:
np.random.randint(100,200,(3,2,2))

array([[[147, 189],
        [145, 152]],

       [[159, 132],
        [135, 114]],

       [[196, 153],
        [159, 178]]])

In [27]:
np.random.randint(100,size=(3,2,2))

array([[[ 6, 14],
        [52, 28]],

       [[48, 79],
        [ 1, 30]],

       [[14, 87],
        [22, 42]]])

In [28]:
import numpy as np
a= np.array([[1,2,7],[4,2,5]])
b= np.array([[1,2,7],[4,6,2]])
print(a)
print(b)
print(a.ndim)
print(b.ndim)

[[1 2 7]
 [4 2 5]]
[[1 2 7]
 [4 6 2]]
2
2


In [29]:
#add

np.add(a,b)

array([[ 2,  4, 14],
       [ 8,  8,  7]])

In [30]:
#subtract
np.subtract(a,b)

array([[ 0,  0,  0],
       [ 0, -4,  3]])

In [31]:
#multiply
np.multiply(a,b)

array([[ 1,  4, 49],
       [16, 12, 10]])

In [32]:
#divide
np.divide(a,b)

array([[1.        , 1.        , 1.        ],
       [1.        , 0.33333333, 2.5       ]])

In [33]:
#floor
import numpy as np
a= np.array([[1,2,3,4,5],[3.5,2,4.9,5.1,9.0]])
print(a)
print(a.shape)
print(a.ndim)
y=np.floor(a)
print(y)

[[1.  2.  3.  4.  5. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
2
[[1. 2. 3. 4. 5.]
 [3. 2. 4. 5. 9.]]


In [34]:

#ceil
import numpy as np
a= np.array([[1,2,3,4,5],[3.5,2,4.9,5.1,9.0]])
print(a)
print(a.shape)
y= np.ceil(a)
print(y)

[[1.  2.  3.  4.  5. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
[[1. 2. 3. 4. 5.]
 [4. 2. 5. 6. 9.]]


In [35]:
import numpy as np
a= np.array([[1,2,3,4,5],[3.5,2,4.9,5.1,9.0]])
print(a)
print(a.shape)
y= np.round(a)
print(y)

[[1.  2.  3.  4.  5. ]
 [3.5 2.  4.9 5.1 9. ]]
(2, 5)
[[1. 2. 3. 4. 5.]
 [4. 2. 5. 5. 9.]]


In [36]:
z=np.rint(a)
print(z)

[[1. 2. 3. 4. 5.]
 [4. 2. 5. 5. 9.]]


In [37]:
print(type(a))

<class 'numpy.ndarray'>


In [38]:
print(a.dtype)

float64


In [39]:
import numpy as np
a= np.array([[1,2,'3',4,5],[3.5,2,4.9,5.1,9.0]])
print(a)
print(a.dtype)

[['1' '2' '3' '4' '5']
 ['3.5' '2' '4.9' '5.1' '9.0']]
<U32


In [40]:
x=a.astype(float)
print(x.dtype)

float64


In [41]:
y=a.astype(complex)
print(y.dtype)

complex128


subsetting

In [42]:
#1d subset
import numpy as np
a= np.array([1,2,'3',4,5])
print(a[2])

3


In [43]:
#2d subset
import numpy as np
a= np.array([[1,2,34,5,6],[14,1,3,5,7,]])
print(a[1,1])

1


In [44]:
import numpy as np
a= np.array([[1,2,'3',4],[1,23,'45',6]])
print(a[0,2])

3


In [45]:
print(a[1,3])

6


In [46]:
#3d subset
import numpy as np
a= np.array([[[1,2,3,4,5],[3,4,5,6,7]],[[1,2,3,4,5],[34,56,7,8,3]]])
print(a[1,1,3])

8


In [47]:
print(a[0,1,3])

6


In [48]:
print(a[1,0,1])

2


1D Slicing:

In [ ]:
import numpy as np
a=np.array([1,2,'3',4,7])
print(a[1:4])

['2' '3' '4']


In [ ]:
import numpy as np
a=np.array([1,2,'3',4,7])
print(a[1:])

['2' '3' '4' '7']


In [ ]:
import numpy as np
a=np.array([1,2,'3',4,7])
print(a[:4])

['1' '2' '3' '4']


2D Slicing:

In [ ]:
import numpy as np
a=np.array([[1,2,'3',4,7],[14,32,'30',40,77]])
print(a.ndim)
print(a[0:2,2:5]) #0th and 1st row and 2nd 3rd 4th columns
print(a[:,1:3])   #0th and 1st row  and 1st 2nd columns

2
[['3' '4' '7']
 ['30' '40' '77']]
[['2' '3']
 ['32' '30']]


3D Slicing:

In [ ]:
import numpy as np
a=np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)
print(a)
print(a.ndim)
print(a[:,1,2:5])
print(a[:,:,1:4])

[[[  1   2   3   4   7]
  [ 14  32  30  40  77]]

 [[ 19  72  38  94  97]
  [ 15 392 320 400 770]]]
3
[[ 30  40  77]
 [320 400 770]]
[[[  2   3   4]
  [ 32  30  40]]

 [[ 72  38  94]
  [392 320 400]]]


Boolean indexing:

In [ ]:
import numpy as np
a=np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)
print(a)
print(a.ndim)
print(a.shape)

[[[  1   2   3   4   7]
  [ 14  32  30  40  77]]

 [[ 19  72  38  94  97]
  [ 15 392 320 400 770]]]
3
(2, 2, 5)


In [ ]:
b=a<100
print(b)

[[[ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True False False False False]]]


Fancy Indexing:

In [ ]:
import numpy as np
a= np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)
print(a[0,0,3])

4


In [ ]:
import numpy as np
a= np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)
print(a[[0],[0],[3]])


[4]


In [ ]:
import numpy as np
a= np.array([[[1,2,'3',4,7],[14,32,'30',40,77]],[[19,72,'38',94,97],[15,392,'320',400,770]]],dtype=int)
print(a[[0,0,1],[0,1,0],[3,1,2]])

[ 4 32 38]


sorting:


In [ ]:
import numpy as np
x= np.array([2,4,3,80,1])
x.sort()
print(x)

[ 1  2  3  4 80]


In [ ]:
import numpy as np
x= np.array([2,4,3,80,1])
y=np.sort(x)[::-1]
print(y)

[80  4  3  2  1]


In [ ]:
import numpy as np
x= np.array([[2,4,3,80,1],[4,14,1,8,10]])
x.sort()
print(x)

[[ 1  2  3  4 80]
 [ 1  4  8 10 14]]


In [ ]:
import numpy as np
x= np.array([[2,4,3,80,1],[4,14,1,8,10]])
y= np.sort(x,axis=1)
print(y)

[[ 1  2  3  4 80]
 [ 1  4  8 10 14]]


In [ ]:
import numpy as np
x= np.array([[2,4,3,80,1],[4,14,1,8,10]])
y= np.sort(x,axis=0)
print(y)

[[ 2  4  1  8  1]
 [ 4 14  3 80 10]]


In [ ]:
import numpy as np
x= np.array([[[2,4,3,80,1],[4,14,1,8,10]],[[20,94,2,8,1],[2,4,3,1,510]]])
x=np.sort(x,axis=0)
print(x)

[[[  2   4   2   8   1]
  [  2   4   1   1  10]]

 [[ 20  94   3  80   1]
  [  4  14   3   8 510]]]


In [ ]:
import numpy as np
x= np.array([[[2,4,3,80,1],[4,14,1,8,10]],[[20,94,2,8,1],[2,4,3,1,510]]])
x=np.sort(x,axis=1)
print(x)

[[[  2   4   1   8   1]
  [  4  14   3  80  10]]

 [[  2   4   2   1   1]
  [ 20  94   3   8 510]]]


copy and view method:

In [ ]:
import numpy as np
x= np.array([3,2,45,6,7,8])
y=x
z=x.copy()
w=x.view()
print(x)
print(y)
print(z)
print(w)
x[2]=405
print(x)
print(y)
print(z)
print(w)

[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[ 3  2 45  6  7  8]
[  3   2 405   6   7   8]
[  3   2 405   6   7   8]
[ 3  2 45  6  7  8]
[  3   2 405   6   7   8]


In [ ]:
#reshape

import numpy as np
a= np.arange(16)
print(a)
print(a.shape)
b=a.reshape(2,8)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [ ]:
b=a.reshape(4,4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
b=a.reshape(4,5)
print(b)

ValueError: cannot reshape array of size 16 into shape (4,5)

resize:

In [ ]:
import numpy as np
a= np.arange(16)
print(a)
print(a.shape)
b= a.resize(4,10)
print(b)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
(16,)
None
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


In [ ]:
import numpy as np
a= np.array([[2,3,4],[4,2,4]])
print(a)
b= a.flatten()
print(b)

[[2 3 4]
 [4 2 4]]
[2 3 4 4 2 4]


In [ ]:
#dot pdt


import numpy as np
a= np.array([[2,3,4],[4,2,4]])
b= np.array([[2,3,4],[4,2,4],[4,2,4]])
print(a)
print('*'*30)
print(b)
print('*'*30)

c=np.dot(a,b)
print(c)

[[2 3 4]
 [4 2 4]]
******************************
[[2 3 4]
 [4 2 4]
 [4 2 4]]
******************************
[[32 20 36]
 [32 24 40]]


In [ ]:
import numpy as np
a= np.array([[[2,3,4],[4,2,4]],[[2,3,4],[4,2,4]]])
b= np.array([[[2,3,4],[4,2,4],[4,2,4]],[[2,3,4],[4,2,4],[4,2,4]]])
print(a)
print('*'*30)
print(b)
print('*'*30)

c=np.dot(a,b)
print(c)

[[[2 3 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]]]
******************************
[[[2 3 4]
  [4 2 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]
  [4 2 4]]]
******************************
[[[[32 20 36]
   [32 20 36]]

  [[32 24 40]
   [32 24 40]]]


 [[[32 20 36]
   [32 20 36]]

  [[32 24 40]
   [32 24 40]]]]


In [ ]:
# min functn

import numpy as np
a= np.array([[[2,3,4],[4,2,4]],[[2,3,4],[4,2,4]]])
print(a)
print('*'*30)
print(a.min())

[[[2 3 4]
  [4 2 4]]

 [[2 3 4]
  [4 2 4]]]
******************************
2


In [ ]:
print(np.min(a))

2


Array joining:

In [49]:
import numpy as np
a= np.array([[[3,4,5],[2,3,4]],[[5,6,7],[9,8,7]]])
b=np.array([[[2,4,6],[1,3,5]],[[6,8,10],[7,9,1]]])
c=np.vstack((a,b))
print(c)


[[[ 3  4  5]
  [ 2  3  4]]

 [[ 5  6  7]
  [ 9  8  7]]

 [[ 2  4  6]
  [ 1  3  5]]

 [[ 6  8 10]
  [ 7  9  1]]]


In [50]:
import numpy as np
a= np.array([[2,3,4],[4,5,6]])
b=np.array([[8,9,7],[5,3,7]])
c= np.row_stack((a,b))
print(c)

[[2 3 4]
 [4 5 6]
 [8 9 7]
 [5 3 7]]


In [51]:
import numpy as np
a=np.array([[2,3,4],[20,30,40]])
b= np.array([[5,6,7],[50,60,70]])
c= np.hstack((a,b))
print(c)

[[ 2  3  4  5  6  7]
 [20 30 40 50 60 70]]


In [52]:
d= np.column_stack((a,b))
print(d)

[[ 2  3  4  5  6  7]
 [20 30 40 50 60 70]]


In [53]:
import numpy as np
a=np.array([[2,3,4],[9,8,7]])
b=np.array([[45,87,21],[67,44,45]])
c= np.concatenate((a,b))
print(c)

[[ 2  3  4]
 [ 9  8  7]
 [45 87 21]
 [67 44 45]]


In [54]:
import numpy as np
a=np.array([[2,3,4],[6,7,8]])
b=np.array([[4,5,6],[1,2,3]])
c= np.concatenate((a,b),axis=1)
print(c)

[[2 3 4 4 5 6]
 [6 7 8 1 2 3]]
